### ISSUE TITLE
Print statements not working in main.py

### ISSUE THREAD

**Issue by nvohra0016** [airex-lab/pdw-simulator#5]
When running the main.py script, the print statements defined in main() do not work. For example, the statement

 **print(f"Simulation complete. PDW data written to {output_file}")** 

does not print anything.

**Comment by protyush19** [comment]
Note that it is not printing in the terminal (which is the default standard output), because the the file "output.txt" is set as the standard output in the beginning of the code of "main.py" file. You can view the content of the print statement towards the end of  "output.txt" file.
